### ISSUE TITLE
Mismatch between how the draft handles dependent blocks, and how the paper describes it

### ISSUE THREAD

**Issue by cipriancraciun** [samuel-lucas6/draft-lucas-balloon-hashing#25]
Looking at the initial paper, it describes the following algorithm for choosing the "dependent blocks":
~~~~
for i from 0 to delta-1:
    block_t idx_block = ints_to_block(t, m, i)
    int other = to_int(hash(cnt++, salt, idx_block)) mod s_cost
    buf[m] = hash(cnt++, buf[m], buf[other])
~~~~

Looking at the current draft, it gives the following steps:
~~~~
pseudorandom = ByteArray(0)
reps = (spaceCost * timeCost * 3) / (HASH_LEN / 4)
for i = 0 to reps - 1
    pseudorandom = pseudorandom || PRF(emptyKey, LE32(VERSION) || personalization || LE32(spaceCost) || LE32(timeCost) || LE32(parallelism) || LE32(iteration) || LE64(counter++))

[...]

        other1 = ReadLE32(pseudorandom.Slice(offset, 4)) % spaceCost
        other2 = ReadLE32(pseudorandom.Slice(offset + 4, 4)) % spaceCost
        other3 = ReadLE32(pseudorandom.Slice(offset + 8, 4)) % spaceCost
        buffer[m] = PRF(key, previous || buffer[m] || buffer[other1] || buffer[other2] || buffer[other3] || LE64(counter++))
        previous = buffer[m]
        offset = offset + 12
~~~~

These two, not only aren't similar, I don't think they even have the same properties.

For example:
* in the initial paper, the choice of each dependent block depends on the current block (i.e. `buffer[m]`;  meanwhile in the draft, the order seems to be completely independent of the current block;
* in the initial paper, each dependent block depends on the contents of the previously chosen dependent block (i.e. there is a sequential process);  in the current draft the three are independent of each other;
* in the initial paper, if one notes the indices of the blocks throughout the execution, they are most likely random;  meanwhile in the current draft, they are completely predictable parametrized only by generally constant parameters like `version`, `personalization`, `spaceCost`, etc. (i.e. the inputs used to generate the `pseudorandom` vector).

Thus, I would say these changes, that greatly simplify the implementation of the round, perhaps greatly impact the security guarantees provided by the initial paper?

**Comment by samuel-lucas6** [comment]
These changes were done for performance rather than simplicity since hashing like that in the original barely uses any of each hash output when computing the memory accesses, and performance is everything with password hashing. Even with these types of changes, this is not a performant algorithm unfortunately.

In both cases, the `other` values can be precomputed, so the difference is:

```
buf[m] = hash(cnt++, buf[m], buf[other1])
buf[m] = hash(cnt++, buf[m], buf[other2])
buf[m] = hash(cnt++, buf[m], buf[other3])
```

vs

```
buffer[m] = PRF(key, previous || buffer[m] || buffer[other1] || buffer[other2] || buffer[other3] || LE64(counter++))
```

In both cases, the current block depends on the current block and 3 other blocks, and you can't process `other2` before `other1` and `other3` before `other2`.

I think this was just a consequence of the pseudocode loop. The textual description in the paper doesn't mention dependency between current blocks, and the reference implementation [doesn't](https://github.com/henrycg/balloon/blob/master/libballoon/hash_state.c#L165) appear to care about this.

**Comment by cipriancraciun** [comment]
> In both cases, the other values can be precomputed, so the difference is: [...]

This is partially true, and now I see your reasoning, but on closer inspection of the paper I also see my reasoning:
* indeed, `other{1..3}` can be precomputed at each iteration, because it doesn't depend on `buf[m]` (my mistake here);
* however, there is one in `s_const` chance that one of the `otherX` variables is `m`, thus there is a chance where the the two algorithms aren't actually the same;  (i.e. `buf[m]` might depend on its "new self" at one of the previous `other` steps;)

----

However, the way the current draft is written, is quite different than the paper when it comes to the PRF usage.  (I've opened ticket #26 about this.)
